{-# LANGUAGE RankNTypes #-}
{-# OPTIONS_GHC -F -pgmF htfpp #-}
module Web.MangoPay.TestUtils where

import Web.MangoPay

import Data.ByteString.Lazy as BS
import Data.Aeson
import Network.HTTP.Conduit
import Data.Conduit
import Data.Maybe
import Test.Framework

-- | test MangoPay API call, logging in with the client credentials
-- expects a file called client.conf containing the JSON of client credentials
-- in the current directory (this file can be generated by mangopay-passphrase
testMP :: forall b.
            (AccessToken -> MangoPayT (ResourceT IO) b)
            -> IO b
testMP f= do
        js<-BS.readFile "client.conf"
        let mcred=decode js
        assertBool (isJust mcred)
        let cred=fromJust mcred
        assertBool (isJust $ cClientSecret cred)
        let s=fromJust $ cClientSecret cred
        withManager (\mgr->
          runMangoPayT cred mgr Sandbox (do
                at<-oauthLogin (cClientID cred) s
                f at
                ))