Hello: Welcome to the MangoPay Yesod demo application
Users: Defined Users:
LnkEvents: Received events...
Events: Received Events:
Next: Next
Previous: Previous

LnkHome: Home

LnkNUserCreate: Create Natural User...
TitleNUser: Natural User
UserFirst: First Name:
UserLast: Last Name:
UserEmail: Email:
UserAddress: Address:
UserBirthday: Birthday:
UserNationality: Nationality:
UserCountry: Country:
UserOccupation: Occupation:
UserIncome: Income:
UserCustomData: Custom Data:
UserProofIdentity: Proof of Identity:
UserProofAddress: Proof of Address:
UserName: Name
UserPersonType: Legal Type
UserHQAddress: HQ Address
UserRepFirst: Representative First Name:
UserRepLast: Representative Last Name:
UserRepEmail: Representative Email:
UserRepAddress: Representative Address:
UserRepBirthday: Representative Birthday:
UserRepNationality: Representative Nationality:
UserRepCountry: Representative Country:
UserStatute: Statute:
UserProofRegistration: Proof of Registration:
UserDeclaration: ShareHolder Declaration:


LnkLUserCreate: Create Legal User...
TitleLUser: Legal User

LnkDoc: Upload document...
LnkUser: Back to user
DocFile: File:
DocCustomData: Custom Data:
DocType: Document Type:
DocStatus: Status:

BtnSubmit: Submit

LnkWalletCreate: Create Wallet...
LnkWallets: Wallets...
WalletCustomData: Custom Data:
WalletDescription: Description:
WalletCurrency: Currency:
WalletBalance: Balance: