Hello: Welcome to the MangoPay Yesod demo application
Users: Defined Users:
LnkEvents: Received events...
Events: Received Events:
Next: Next
Previous: Previous

TitleEvents: Events
LnkHome: Home

LnkNUserCreate: Create Natural User...
TitleNUser: Natural User
UserFirst: First Name:
UserLast: Last Name:
UserEmail: Email:
UserAddress: Address:
UserBirthday: Birthday:
UserNationality: Nationality:
UserCountry: Country:
UserOccupation: Occupation:
UserIncome: Income:
UserCustomData: Custom Data:
UserProofIdentity: Proof of Identity:
UserProofAddress: Proof of Address:
UserName: Name
UserPersonType: Legal Type
UserHQAddress: HQ Address
UserRepFirst: Representative First Name:
UserRepLast: Representative Last Name:
UserRepEmail: Representative Email:
UserRepAddress: Representative Address:
UserRepBirthday: Representative Birthday:
UserRepNationality: Representative Nationality:
UserRepCountry: Representative Country:
UserStatute: Statute:
UserProofRegistration: Proof of Registration:
UserDeclaration: ShareHolder Declaration:


LnkLUserCreate: Create Legal User...
TitleLUser: Legal User

LnkDoc: Upload document...
LnkUser: Back to user
TitleDocument: Upload a document
DocFile: File:
DocCustomData: Custom Data:
DocType: Document Type:
DocStatus: Status:

BtnSubmit: Submit

LnkWalletCreate: Create Wallet...
LnkWallets: Wallets...
TitleWallets: Wallets
TitleWallet: Wallet
WalletCustomData: Custom Data:
WalletDescription: Description:
WalletCurrency: Currency:
WalletBalance: Balance:

LnkCardCreate: Register Card...
LnkCards: Cards...
TitleCards: Cards
TitleCard: Card
CardCurrency: Currency:
CardNumber: Number:
CardExpire: Expiry Date:
CardCSC: Security Code:

LnkAccountCreate: Create Account...
LnkAccounts: Accounts...
TitleAccounts: Accounts
TitleAccount: Account
AccountCustomData: Custom Data:
AccountOwnerName: Owner Name:
AccountOwnerAddress: Owner Address:
AccountIBAN: IBAN:
AccountBIC: BIC:

ErrorData: Invalid data
CardDone: Card registration done
WalletDone: Wallet change submitted
UserDone: User change submitted
AccountDone: Account registration done
DocDone: Document uploaded
ErrorDoc: Error while uploading document

LnkTransactions: Transactions...
TitleTransactions: Transactions
PastTransactions: Past transactions:

TitlePayIn: Pay-In
LnkPayIn: Make Pay-In
PayInDone: Pay-In done
PayInCard: From Card:
PayInWallet: To Wallet:
PayInAmount: Amount:
PayInCurrency: Currency:

TitleTransfer: Transfer
LnkTransfer: Make Transfer
TransferDone: Transfer done
TransferToUser: To User:
TransferFromWallet: From Wallet:
TransferToWallet: To Wallet:
TransferAmount: Amount:
TransferCurrency: Currency:

TitlePayOut: Pay-Out
LnkPayOut: Make Pay-out
PayOutDone: Pay-Out done
PayOutWallet: From Wallet:
PayOutAccount: To Account:
PayOutAmount: Amount:
PayOutCurrency: Currency:

RequestFail: Request to Mangopay failed

UserCreate: Create new user
UserModify id@Text : Modify user # #{id}
WalletCreate: Create new wallet
WalletModify id@Text : Modify wallet # #{id}
